/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package org.szakdoli.bigbuttons;


import java.util.Arrays;
import javax.swing.JOptionPane;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.szakdoli.bigbuttons//menufele//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "menufeleTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "org.szakdoli.bigbuttons.menufeleTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_menufeleAction",
        preferredID = "menufeleTopComponent"
)
@Messages({
    "CTL_menufeleAction=menufele",
    "CTL_menufeleTopComponent=menufele Window",
    "HINT_menufeleTopComponent=This is a menufele window"
})
public final class menufeleTopComponent extends TopComponent {

    public menufeleTopComponent() {
        initComponents();
        setName(Bundle.CTL_menufeleTopComponent());
        setToolTipText(Bundle.HINT_menufeleTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);
        jPanel1.setVisible(false);

    }

    void  admin(){
        char[] pw = new char[]{'a','d','m','i','n'};
        String user = "admin";
        if (Arrays.equals(jPasswordField1.getPassword(), pw)  &&jTextField1.getText().equals(user)) {
          
             jPanel1.setVisible(true);
        jPanel2.setVisible(false);
                btnKolcson.setVisible(true);
        btnBook.setVisible(true);
        btnTag.setVisible(true);
        btnmanager.setVisible(true);
          JOptionPane.showMessageDialog(null, "Sikeres bejelentkezés!");
            jPasswordField1.setText("");
            jTextField1.setText("");
        }else {
            JOptionPane.showMessageDialog(null, "A megadott adatok nem megfelelőek!");
            jPasswordField1.setText("");
            jTextField1.setText("");
        }
       
    }
     
    
    void vendeg(){
                     jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        btnKolcson.setVisible(false);
        btnBook.setVisible(false);
        btnTag.setVisible(false);
        btnmanager.setVisible(false);
         JOptionPane.showMessageDialog(null, "Sikeres bejelentkezés!");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBook = new javax.swing.JButton();
        btnKolcson = new javax.swing.JButton();
        btnmanager = new javax.swing.JButton();
        btnTag = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 140, 50));

        jTextField1.setText(org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.jTextField1.text")); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 230, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 140, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 240, 60));

        jPasswordField1.setText(org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.jPasswordField1.text")); // NOI18N
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.jLabel2.text")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.jLabel3.text")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, 30));

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBook.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnBook, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.btnBook.text")); // NOI18N
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 210, 60));

        btnKolcson.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnKolcson, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.btnKolcson.text")); // NOI18N
        btnKolcson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKolcsonActionPerformed(evt);
            }
        });
        jPanel1.add(btnKolcson, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 210, 60));

        btnmanager.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnmanager, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.btnmanager.text")); // NOI18N
        btnmanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnmanager, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 210, 60));

        btnTag.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnTag, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.btnTag.text")); // NOI18N
        btnTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagActionPerformed(evt);
            }
        });
        jPanel1.add(btnTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 210, 60));

        btnRead.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnRead, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.btnRead.text")); // NOI18N
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        jPanel1.add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 210, 60));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(menufeleTopComponent.class, "menufeleTopComponent.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagerActionPerformed
       WindowManager.getDefault().findTopComponent("ManagerTopComponent").open(); 
        WindowManager.getDefault().findTopComponent("ManagerTopComponent").requestActive(); 
       
    }//GEN-LAST:event_btnmanagerActionPerformed

    private void btnKolcsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKolcsonActionPerformed
        WindowManager.getDefault().findTopComponent("borrowBooksTopComponent").open(); 
        WindowManager.getDefault().findTopComponent("borrowBooksTopComponent").requestActive(); 
    }//GEN-LAST:event_btnKolcsonActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
         WindowManager.getDefault().findTopComponent("addbooksTopComponent").open(); 
        WindowManager.getDefault().findTopComponent("addbooksTopComponent").requestActive(); 
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
         WindowManager.getDefault().findTopComponent("pdfolvasoTopComponent").open(); 
        WindowManager.getDefault().findTopComponent("pdfolvasoTopComponent").requestActive(); 
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagActionPerformed
         WindowManager.getDefault().findTopComponent("addmemberTopComponent").open(); 
        WindowManager.getDefault().findTopComponent("addmemberTopComponent").requestActive(); 
    }//GEN-LAST:event_btnTagActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       admin();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      jPanel1.setVisible(false);
      jPanel2.setVisible(true);
      JOptionPane.showMessageDialog(null, "Kijelentkeztél!");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      vendeg();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnKolcson;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnTag;
    private javax.swing.JButton btnmanager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
